### ISSUE TITLE
[БАГ] Таблица Ведомостей. При повторном нажатии на выбор группы в селекте очищается таблица

### ISSUE THREAD

**Issue by Hardome** [NasDiK/PI-S2-OnlineCoursesService#65]
1) Пофиксить отображение ролей на странице Админ-панель (вкладка назначения ролей), сейчас отображается name роли, а должно title.
2) Пофиксить таблицу ведомостей на странице Мои студенты. Сейчас при повторном нажатии на выбор группы в селекте очищается таблица, а не должна.

**Comment by NasDiK** [comment]
Напиши нормальное описание и название. В чем баг заключается
