### ISSUE TITLE
[Баг]: Не всегда выводятся ответы в таблицу моих студентов

### ISSUE THREAD

**Issue by Hardome** [NasDiK/PI-S2-OnlineCoursesService#72]
Сейчас могут быть пустые ячейки ответов, должны быть заполнены всегда
![image](https://github.com/NasDiK/PI-S2-OnlineCoursesService/assets/103805048/15054f57-8134-409e-bcb1-96c369fabfb3)
Можно вызывать метод группировки ответов после получения всех запросов на бэк

**Comment by NasDiK** [comment]
Нужно, а не можно. хД
